import React from 'react';
import { BookOpen, HelpCircle, Link2, BarChart2 } from 'lucide-react';
import { MA } from './matchAnalysisTheme';

// "הסיפור המלא" — the expanded deep-analysis narrative shown when the coach
// opens the deep view. Driven by MatchAnalysis.deep_analysis (generated by the
// generateDeepAnalysis edge function).
export default function DeepAnalysisStory({ deep }) {
  if (!deep) return null;

  return (
    <div className="ma-fade" style={{
      background: MA.card, borderRadius: 16, padding: '20px 22px',
      boxShadow: MA.cardShadow, borderRight: `4px solid ${MA.greenMain}`,
    }}>
      <h3 style={{
        margin: '0 0 10px', fontSize: 14, fontWeight: 800, fontFamily: MA.heading,
        color: MA.textPrimary, display: 'flex', alignItems: 'center', gap: 8,
      }}>
        <BookOpen style={{ width: 15, height: 15, color: MA.greenMain }} />
        ניתוח מעמיק — הסיפור המלא של המשחק
        {deep.data_richness && (
          <span style={{
            fontSize: 11, fontWeight: 600, padding: '2px 8px', borderRadius: 9999,
            background: deep.data_richness === 'sparse' ? MA.warnBg : MA.successBg,
            color: deep.data_richness === 'sparse' ? MA.warn : MA.greenMain,
          }}>
            {deep.data_richness === 'sparse' ? 'מבוסס הערות מאמן' : 'מבוסס נתוני משחק'}
          </span>
        )}
      </h3>

      {deep.story && (
        <p style={{ margin: '0 0 10px', fontSize: 13, lineHeight: 1.8, color: MA.textSecondary }}>
          {deep.story}
        </p>
      )}

      {/* How the training topics tie back to what happened */}
      {deep.training_topic_context?.length > 0 && (
        <div style={{ marginTop: 14 }}>
          <h4 style={{ margin: '0 0 8px', fontSize: 12, fontWeight: 800, fontFamily: MA.heading, color: MA.textPrimary, display: 'flex', alignItems: 'center', gap: 6 }}>
            <Link2 style={{ width: 13, height: 13 }} /> איך נושאי האימון מתחברים למשחק
          </h4>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {deep.training_topic_context.map((t, i) => (
              <div key={i} style={{ borderRadius: 12, padding: '10px 12px', background: MA.successBg }}>
                <p style={{ margin: 0, fontSize: 12, fontWeight: 700, color: MA.greenMain }}>{t.topic}</p>
                <p style={{ margin: '3px 0 0', fontSize: 12, lineHeight: 1.65, color: MA.textSecondary }}>{t.story_link}</p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Only surfaced when the match data was thin */}
      {deep.clarifying_questions?.length > 0 && (
        <div style={{ marginTop: 14, borderRadius: 12, padding: '12px 14px', background: MA.warnBg }}>
          <h4 style={{ margin: '0 0 4px', fontSize: 12, fontWeight: 800, fontFamily: MA.heading, color: MA.warn, display: 'flex', alignItems: 'center', gap: 6 }}>
            <HelpCircle style={{ width: 13, height: 13 }} /> שאלות שיעזרו לניתוח הבא
          </h4>
          <p style={{ margin: '0 0 8px', fontSize: 11, color: MA.textMuted }}>
            המידע מהמשחק הזה היה מצומצם — התשובות יעזרו להעמיק בפעם הבאה (אפשר לדלג):
          </p>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
            {deep.clarifying_questions.map((q, i) => (
              <div key={i}>
                <p style={{ margin: 0, fontSize: 12, fontWeight: 600, color: MA.textPrimary, display: 'flex', gap: 6 }}>
                  <span style={{
                    flexShrink: 0, width: 18, height: 18, borderRadius: 9999, background: 'rgba(217,119,6,.18)',
                    color: MA.warn, fontSize: 10, fontWeight: 800, display: 'flex', alignItems: 'center', justifyContent: 'center',
                  }}>{i + 1}</span>
                  <span>{q.question}</span>
                </p>
                {q.reason && (
                  <p style={{ margin: '2px 0 0 0', paddingInlineStart: 24, fontSize: 11, lineHeight: 1.6, color: MA.textMuted }}>{q.reason}</p>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {deep.issue_expansions?.some(e => e.supporting_data) && (
        <p style={{ margin: '12px 0 0', paddingTop: 10, borderTop: '1px dashed rgba(13,26,18,.1)', fontSize: 11, color: MA.textMuted, display: 'flex', alignItems: 'center', gap: 6 }}>
          <BarChart2 style={{ width: 12, height: 12 }} />
          ההסברים המלאים לכל בעיה מוצגים בכרטיס "בעיות טקטיות שזוהו"
        </p>
      )}
    </div>
  );
}
